ChannelEngineWeb/ChannelEngine.Web/Models/ErrorViewModel.cs
namespace ChannelEngine.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ChannelEngineWeb/ChannelEngine.Web/Controllers/HomeController.cs
using ChannelEngine.Models.Models;
using ChannelEngine.Services.Intefaces;
using ChannelEngine.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ChannelEngine.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IOrderService _orderService;
        private readonly IProductService _productService;
        public HomeController(ILogger<HomeController> logger, IOrderService orderService, IProductService productService)
        {
            _logger = logger;
            _orderService = orderService;
            _productService = productService;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ChannelEngineWeb/ChannelEngine.Web/Controllers/OrderController.cs
using ChannelEngine.Services.Intefaces;
using Microsoft.AspNetCore.Mvc;

namespace ChannelEngine.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                var orders = await _orderService.GetAllOrdersByStatusType();
                return View(orders);
            }
            catch (Exception ex)
            {
                return View();
            }
        }
    }
}

ChannelEngineWeb/ChannelEngine.Web/Controllers/ProductController.cs
using ChannelEngine.Models.Models;
using ChannelEngine.Services.Intefaces;
using Microsoft.AspNetCore.Mvc;

namespace ChannelEngine.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IOrderService _orderService;
        public ProductController(IProductService productService
            ,IOrderService orderService)
        {
            _productService = productService;
            _orderService = orderService;
        }

        public async Task<IActionResult> Index()
        {
            var topSoldOrders = await _orderService.GetOrdersAccordingToQuantity(5);
            return View(topSoldOrders);
        }
        public async Task<IActionResult> UpdateStock(string productNo)
        {
            if (!string.IsNullOrWhiteSpace(productNo))
            {
                List<ProductRequestModel> productRequestModels = new List<ProductRequestModel>();
                var productRequestModel = new ProductRequestModel()
                {
                    MerchantProductNo = productNo,
                    Stock = 25
                };
                productRequestModels.Add(productRequestModel);
                var response = await _productService.UpdateProductAsync(productRequestModels);
                ViewBag.Response = response;
                return View("Index");
            }
            return View("Index");
        }
    }
}

ChannelEngineWeb/ChannelEngine.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This is ChannelEngine assessment Project.</p>
</div>

ChannelEngineWeb/ChannelEngine.Web/Views/Order/Index.cshtml
@using ChannelEngine.Models.Models
@model ChannelEngine.Models.Models.ApiResultModel<OrderCollectionsModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Order InProgress</h1>

@if (Model != null && Model.Success)
{
    <div class="container">
        <div class="row">
            <table class="table">
                <thead>
                    <tr>
                        <th>Channel Name</th>
                        <th>Channel Order No</th>
                        <th>Customer No</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var order in Model.ResponseData.Content)
                    {
                        <tr>
                            <td>@order.ChannelName</td>
                            <td>@order.ChannelOrderNo</td>
                            <td>@order.ChannelCustomerNo</td>
                            <td>@order.Status</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}

ChannelEngineWeb/ChannelEngine.Web/Views/Product/Index.cshtml
@using ChannelEngine.Models.UIModels
@model ChannelEngine.Models.Models.ApiResultModel<List<OrderLineModel>>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Top Quantity List Page</h1>

@if (Model != null && Model.Success)
{
    <div class="container">
        <div class="row">
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Quantity</th>
                        <th>Product No</th>
                        <th>Gtin</th>
                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var product in Model.ResponseData)
                    {
                        <tr>
                            <td>@product.ProductDescription </td>
                            <td>@product.Quantity </td>
                            <td>@product.ProductNo </td>
                            <td>@product.Gtin </td>
                            <td>@Html.ActionLink($"Update Product Stock - {product.ProductNo}", "UpdateStock", "Product", new { productNo = product.ProductNo })</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}
@if (ViewBag.Response != null)
{
    if (ViewBag.Response.Success == true)
    {
        <div class="row">
            <span>
                <label>
                    the product is The product stock has been updated to 25.
                </label>
            </span>
        </div>
    }
    else
    {
        <div class="row">
            <span>
                <label>
                    An error has been occured while the product is updating.
                </label>
            </span>
        </div>
    }
}

ChannelEngineWeb/ChannelEngine.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChannelEngine.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ChannelEngine.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChannelEngine.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders (InProgress)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ChannelEngine.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>